### ISSUE TITLE
Create method overrides provided `id` attribute

### ISSUE THREAD

**Issue by coreyward** [deepcerulean/passive_record#7]
The `create` method doesn't check for an ID passed in attributes before assigning one: https://github.com/deepcerulean/passive_record/blob/master/lib/passive_record/class_methods.rb#L56

I was considering using PassiveRecord to traverse a relational object structure that is JSON-backed and non-persisting. The objects have IDs that I need to use to map back to another part of the system.

If desired, the change could be as simple as:

```ruby
instance_id = attrs.delete(:id) || SecureRandomIdentifier.generate(self)
instance.send(:id=, instance_id)
```

**Comment by jweissman** [comment]
Thanks so much for reporting this!

**Comment by jweissman** [comment]
A quick note here as I'm digging in a little bit -- you're right that `create` doesn't check for the ID before assigning one. 

However, when you pass an `id` attribute in, the value you provide will end up overriding the 'default' id since `create` works through the attributes one by one, assigning each one.

This means that the following test (which I was writing trying to exhibit the problem) already passes:

  `expect(SomeModel.create(id: 'the_id').id).to eq('the_id')`

It's possible that PassiveRecord might be working as you expect here, despite a possibly misleading-looking implementation (which means it probably ought to be clarified.)

If only for performance reasons I definitely like the idea of not building a new UUID if we don't have to.

**Comment by jweissman** [comment]
Okay, as of https://github.com/deepcerulean/passive_record/commit/e646bc7f6c7fe9fda19c85a6a499d4bfb5def78a we're no longer generating UUIDs if we're passed in the ID (this is based mostly on your suggestion). 

Thanks again for pointing this out!

**Comment by coreyward** [comment]
Hey @jweissman — my concern was that `register` gets called with the UUID before the `attrs[:id]` has a chance to override it. Might be worthwhile to add a test to ensure relationships are looked up correctly when a user provides an ID in the attributes passed to `create`, though it looks like the new implementation will do that. 

Cheers!
